vehicle_wmi = {
  'Saturn': ['1G8', '3GS', '5GZ', 'W08'],
  'Mahindra': ['MA1'],
  'Suzuki Canada': ['2S3'],
  'Bentley': ['SCB', 'SJA'],
  'Volkswagen USA (Commercials)': ['1V1'],
  'Land Rover': ['SAL', 'SUR'],
  'Daihatsu': ['JDA'],
  'Mini': ['WMW'],
  'Honda Mexico': ['3CZ'],
  'Mitsubishi (NedCar)': ['XMC'],
  'AM': ['137'],
  'GAC Fiat': ['LWV'],
  'Fliegl': ['WFD'],
  'CAMI': ['2CN'],
  'Volkswagen Commercial Vehicles': ['WV1', 'WV2'],
  'Changan Suzuki': ['LS5'],
  'GAC Toyota': ['LVG'],
  'Beijing Benz': ['LE4'],
  'Dacia': ['UU'],
  'Plymouth': ['1P3', '1P4', '2P3', '2P4'],
  'Smart': ['WME'],
  'NUMMI': ['1NX'],
  'JAC': ['LJ1'],
  'Suzuki': ['2S2', '5Z6', '8AK', 'JS', 'KL5', 'MA3', 'MMS', 'TSM'],
  'MAN': ['6AB', 'LZM', 'WMA'],
  'Fiat Professional': ['93W'],
  'Ram': ['1C6', '3C6', '3C7'],
  'SAIC GM Wuling': ['LZW'],
  'Mercedes Benz': ['8AC', '9BM'],
  'CAOA / Hyundai': ['95P'],
  'Peugeot UK': ['SDB'],
  'Honda Siel Cars': ['MA7'],
  'Suzhou King Long': ['LKL'],
  'Saab': ['3G0', '5S3', 'JF4', 'YK1', 'YS3'],
  'Chery': ['98R', '9UJ', 'LVV'],
  'Ferrari': ['ZFF'],
  'Porsche SUV': ['WP1'],
  'Subaru': ['1F2', '4S3', '4S4', 'JF2', 'JFS'],
  'Lexus': ['58A', 'JT6', 'JT8', 'JTH', 'JTJ'],
  'Hyundai Motor Company / Hyundai': ['9BH'],
  'Mazda Mexico': ['3MY', '3MZ'],
  'Ford Otosan': ['NM0'],
  'JLR Jaguar Land Rover': ['99J'],
  'Tauro Sport Auto': ['VV9'],
  'Changan Ford': ['LVS'],
  'Volvo China': ['LYV'],
  'Brilliance Zhonghua': ['LSY'],
  'Proton': ['PL1'],
  'Suzuki Motorcycles': ['9CD'],
  'Scion': ['1TK', 'JF1', 'JTK', 'JTL', 'JTN'],
  'Mercedes-Benz (Sprinter)': ['WCD', 'WDP', 'WDR', 'WDY', 'WDZ'],
  'Dodge': ['1B', '1C4', '1D', '2B4', '2B5', '2B6', '2B7', '2B8', '2C7', '2D3', '2D6', '2D7', '3B6', '3D', '4B3', 'JB3', 'KC4', 'WD0', 'WD2', 'WD5', 'WDW', 'WDX'],
  'Peugeot': ['8AD', '8GD', '936', 'FV3', 'VF3', 'VFF', 'VS3', 'WF3'],
  'Iveco': ['8AT', '93Z', 'VS1', 'WJM', 'ZCF'],
  'Western Star': ['2W'],
  'SAIC Volkswagen': ['LSV'],
  'Volvo Eicher commercial vehicles limited.': ['MC2'],
  'Opel (Opel/Vauxhall)': ['W0L'],
  'Neoplan': ['WAG'],
  'Great Wall (Havel)': ['LGW'],
  'Chevrolet': ['124', '1G1', '1GA', '1GC', '1Y1', '2G1', '309', '3G1', '3GV', '3N6', '4G1', '54D', '6G1', '8GG', 'JGN', 'KL1', 'KL7', 'KL8', 'KLA', 'MMM', 'Z3B'],
  'LDV': ['SEY'],
  'Volkswagen Spain': ['VWG'],
  'Roadrunner Hay Squeeze': ['1R9'],
  'GMC Truck': ['1GT'],
  'Sterling': ['2FZ'],
  'Shaanxi Automobile Group': ['LZG'],
  'Mack Truck': ['1M1', '1M2', '1M3', '1M4'],
  'Porsche car': ['WP0'],
  'Buick China': ['LRB'],
  'FAW-Volkswagen': ['LFV'],
  'Plymouth Mexico': ['3P3'],
  'Pontiac': ['1G2', '1GM', '2CK', '2G2', '3G2', '3G7', '5Y2', '6G2', 'KL2'],
  'DaimlerChrysler AG/Daimler AG': ['WDC', 'WDD', 'WMX'],
  'Audi': ['93U', '99A', 'TRU', 'WA1', 'WAU', 'WAV', 'WMB'],
  'Renault': ['8A1', '93Y', '9FB', 'CF1', 'FV1', 'GA1', 'VF1', 'VF2', 'VFB', 'VFJ', 'VNV', 'VS5', 'VSY', 'VW1', 'WF1', 'X7L'],
  'Dongfeng Yueda Kia': ['LJD'],
  'Rover': ['SAR', 'SAX'],
  'Fiat Automobiles': ['ZFA'],
  'Mazda': ['1YV', '3MD', '4F', 'JM', 'MM0', 'MM8', 'PE3', 'YCM'],
  'Ducati Motor Holdings SpA': ['ZDM'],
  'EvoBus': ['WEB'],
  'Cadillac': ['1G6', '1GE', '1GY', '2G6', '2GE', '3GY', 'B01', 'G61', 'W06'],
  'MINI': ['WMZ'],
  'Piaggio/Vespa/Gilera': ['ZAP'],
  'Honda Motorcycles': ['9C2'],
  'Lamborghini': ['ZHW'],
  'Hyundai/Kia': ['5X'],
  'Lada (AvtoVAZ)': ['XTA'],
  'Lifan': ['9UK', 'LLV'],
  'Wallyscar': ['CL9'],
  'Chrysler Mexico': ['3A'],
  'Scania': ['9BS', 'VLU'],
  'Karosa': ['TMK', 'TN9'],
  'Scania, Södertälje': ['YS2'],
  'Lexus Canada': ['2T2'],
  'Hummer': ['5GN', '5GR', '5GT'],
  'Chevrolet Mexico': ['3GC', '3GN'],
  'Merato Motorcycle Taizhou Zhongneng': ['L5Y'],
  'Dodge Canada': ['2B3', '2D4', '2D8'],
  'Mclaren': ['SBM'],
  'Fiat Auto Poland / FSM': ['SUF'],
  'Fuji Heavy Industries': ['JF'],
  'Ferrari Dino': ['ZDF'],
  'Kenworth': ['1XK', '6F5'],
  'Rolls Royce': ['SCA'],
  'Ikarus Egyedi Autobuszgyar': ['TSE'],
  'Aprilia': ['ZD4'],
  'Dongfeng Nissan': ['LGB'],
  'Toyota': ['2T', '4T', '5T', '5YF', '602', '6T1', '8AJ', '93R', '9BR', 'AHT', 'JT', 'JTD', 'JTE', 'JTM', 'JTS', 'MR0', 'NMT', 'SB1', 'STE', 'VNK', 'WNK', 'YAR'],
  'KIA Myanmar': ['MS0'],
  'GAC Trumpchi': ['LMG'],
  'Aixam': ['VLG'],
  'Irmscher': ['WJR'],
  'FAW Toyota (Tianjin)': ['LTV'],
  'Isuzu Guangzhou': ['LZE'],
  'Nova Bus': ['2NV', '4RK'],
  'Opel': ['4GD', 'SED', 'SKF', 'V0L', 'VN1', 'VSX', 'W00', 'W0V', 'WOL', 'XUF', 'XWF', 'Y6D', 'Z12'],
  'Hyundai': ['2HM', '5NM', '5NP', 'KM', 'MAL', 'NLH', 'NLJ', 'TMA'],
  'Volvo': ['4V', 'LVY', 'VY1', 'XLB'],
  'IvecoBus': ['VFE', 'ZGA'],
  'Tata': ['MAT'],
  'Bugatti': ['VF9', 'ZA9'],
  'Microcar': ['VH8'],
  'Spyker': ['XL9'],
  'BMW Brilliance': ['LBV'],
  'Mercedes-Benz Turk Truck': ['NLE'],
  'Seat': ['VSZ', 'WSS'],
  'SOR': ['TK9'],
  'Mercedes-Benz Argentina': ['8BR', '8BT'],
  'Freightliner': ['1FU', '1FV', '2FU', '2FV'],
  'FWD Corp.': ['1F9'],
  'Buick': ['04W', '1G4', '2G4', '3G5', '5GA', 'G4G', 'KL4', 'L4C', 'W04'],
  'Replica/Kit Makes': ['119', '601'],
  'Ford': ['0VF', '17V', '1F', '210', '2F', '3F', '6F', '8AF', '9BF', 'AFA', 'MNB', 'PE1', 'SFA', 'VF0', 'VS6', 'WE0', 'WFO', 'WS0', 'WV0'],
  'Harley-Davidson': ['1HD'],
  'Dodge Mexico': ['3B7', '3C4'],
  'Fiat Automóveis': ['9BD'],
  'Mercury Mexico': ['3ME'],
  'General Motors-Holden': ['6H8'],
  'Fiat V.I.': ['ZFC'],
  'Škoda': ['TMB'],
  'Triumph': ['SAT', 'SMT'],
  'Holden': ['6H'],
  'Renault (Renault Dacia)': ['UU1'],
  'Dongfeng Honda': ['LVH'],
  'Suzuki / Santana Motors': ['VSE'],
  'Solaris Bus & Coach': ['SU9'],
  'BMW': ['4US', '5U', '5YM', '98M', 'KRX', 'WB', 'WBA', 'WBX', 'WBY'],
  'BMW M': ['WBS'],
  'Karl Kässbohrer Fahrzeugwerke': ['WKK'],
  'Dong Feng (DFM), China': ['LGH'],
  'Frt-Thomas Bus': ['4UZ'],
  'QUANTYA Swiss Electric Movement': ['TDM'],
  'Scania, Katrineholm': ['YS4'],
  'Nissan (Infiniti)': ['5N3', 'JNK', 'JNR', 'JNT', 'JNX', 'SJK'],
  'Maserati': ['000', 'ZAM', 'ZN6'],
  'Mitsubishi Thailand': ['ML3'],
  'Mercury': ['1M', '1ME', '1ZW', '2M', '4M', 'FM2'],
  'Fiat Automobiles/Mazda': ['JC1'],
  'Irisbus': ['VNE'],
  'Cagiva SpA': ['ZCG'],
  'Nissan (Nissan Motor Company)': ['6F4'],
  'Aston Martin Lagonda Limited': ['SCF'],
  'Lancia': ['ZLA'],
  'Souza Ramos - Mitsubishi / Suzuki': ['93X'],
  'Ruf Automobile': ['W09'],
  'Micro Compact Car AG (SMART 1998-1999)': ['TCC'],
  'FAW Haima': ['LH1'],
  'Citroën': ['8BC', '935', 'VF7'],
  'Audi Brazil': ['93V'],
  'Citroen': ['FV7', 'VFG', 'VFZ', 'VS7', 'WF7'],
  'Alfa Romeo': ['ZAR'],
  'Tatra': ['TMT'],
  'Jeep': ['1J', '1J4', '1J8', '1L4', '988', 'SNE'],
  'Auto Alliance International': ['1ZV'],
  'Google': ['1G9'],
  'Daimler AG (Sprinter)': ['WD3', 'WD4', 'WDA'],
  'Iveco Unic SA': ['VF5'],
  'Zastava / Yugo': ['VX1'],
  'Zhongtong Coach': ['LDY'],
  'FordS': ['MAJ'],
  'Mercedes-Benz': ['115', '123', '460', '4J', '55',  '55S', 'EDB', 'VSA', 'W1', 'WBD', 'WD8', 'WDB', 'WDF', 'WWD', 'X96'],
  'GMC': ['1GD', '1GJ', '1GK', '2GK', '2GT', '3GD', '3GK', '3GT', 'GKA'],
  'Ontario Drive & Gear': ['2DG'],
  'Acura': ['19', '2HH', '2HN', '5FR', '5J8', 'JAE', 'JH4'],
  'Volvo Trucks': ['9BV', 'YV2'],
  'Fisker': ['YH4'],
  'Saab NEVS': ['YTN'],
  'Carrocerias Ayats': ['VS9'],
  'Chevrolet USA': ['1GB', '1GN'],
  'Subaru-Isuzu Automotive': ['4S'],
  'OM': ['ZOM'],
  'Chevrolet Australia': ['6G3'],
  'DeLorean': ['SCE'],
  'BYD Auto': ['LGX'],
  'Geely': ['L6T'],
  'Opel (Opel Special Vehicles)': ['W0S'],
  'Chevrolet Canada': ['2GC', '2GN'],
  'Daewoo Poland / FSO': ['SUL', 'SUP'],
  'Škoda trolleybuses': ['TM9', 'TMP'],
  'Ikarus Bus': ['TRA'],
  'Gnome Homes': ['2G9'],
  'Daewoo/GM Korea': ['KL'],
  'Honda': ['19X', '1H', '2H', '3H', '4S6', '5F', '5J6', '5KB', '7A3', '7FA', '8C3', '93H', 'JH', 'JHM', 'LUC', 'MHR', 'MRH', 'NLA', 'SAH', 'SHH', 'SHS', 'SNT', 'XXX'],
  'Tesla': ['5YJ'],
  'Dongfeng Fengshen': ['LGJ'],
  'Lincoln': ['1CN', '1L', '1L1', '1LN', '2L', '2L1', '2LM', '2LN', '3LN', '5L', 'KLM'],
  'FAW Car': ['LFP'],
  'Renault (Renault Samsung)': ['KNM', 'L56'],
  'Genesis': ['KMH'],
  'FAW Toyota': ['LFM'],
  'Alpina': ['WAP'],
  'Fiat': ['3C3', '8AP', 'ZAF', 'ZFB', 'ZSA'],
  'Alexander Dennis': ['SFD'],
  'Volkswagen Trucks': ['WV3'],
  'Volkswagen': ['112', '117', '1V2', '1VW', '2V4', '2V8', '3VV', '3VW', '8AW', '9BW', 'AAV', 'VW2', 'VWV', 'WUW', 'WV', 'WVG', 'WVW', 'WVZ', 'WWW', 'WYG', 'WYW', 'WZW', 'XW8'],
  'Kia': ['3KP', '5XX', '5XY', '9UW', 'KN', 'U5Y', 'U6Y', 'USY', 'XWE'],
  'SsangYong': ['KP', 'WAX'],
  'Beijing Hyundai': ['LBE'],
  'SEAT': ['VSS'],
  'FSM': ['FSM'],
  'Volvo Cars': ['YV1', 'YV4'],
  'Ford Motor Company': ['6FP'],
  'Volvo Buses': ['YV3'],
  'Quattro': ['WUA'],
  'Renault Trucks/Volvo': ['VF6'],
  'Toyota Mexico': ['3TM'],
  'Mynatt Truck & Equipment': ['1M9'],
  'Yamaha': ['9C6', 'JY'],
  'Dongfeng Peugeot-Citroën': ['LDC'],
  'Oldsmobile': ['1G3', '1GH', '2G3'],
  'Kawasaki': ['JK'],
  'VW Trucks / MAN': ['953'],
  'BYD Bus': ['LC0'],
  'SAIC General Motors': ['LSG'],
  'Talbot': ['VF4'],
  'Guangzhou Honda': ['LHG'],
  'Changan PSA (DS Automobiles)': ['LPA'],
  'Changan Mazda': ['LVR'],
  'Yutong': ['LZY'],
  'SAIC MG': ['LSJ'],
  'Nissan': ['1JN', '1N', '1V4', '3N', '4N2', '5BZ', '5N1', '5NA', '94D', 'JN', 'KN1', 'MBH', 'MDH', 'MNT', 'SJN', 'VSK', 'VWA'],
  'ÖAF': ['VA0'],
  'Peterbilt': ['1XP'],
  'Skoda': ['TNB', 'YMB'],
  'Ford of Europe': ['WF0'],
  'Isuzu': ['1GG', '4NU', '4S2', 'JA', 'JAC', 'MP1', 'MPA'],
  'Matra/Talbot/Simca': ['VF8'],
  'FCA': ['ZAC'],
  'Mitsubishi': ['1Z3', '1Z7', '4A', '6MM', 'JA3', 'JA4', 'JMB', 'MMB', 'MMC', 'MMT', 'TYB', 'XNC'],
  'General Motors': ['1G', '2CT', '2G', '3G', '6G', '8AG', '9BG'],
  'Chrysler': ['1A4', '1A8', '1C', '1C8', '2C3', '2C8', '3A4', '3A8', '3C', '3C8', '4C3', 'TC3'],
  'Tofas Turk': ['NM4'],
  'Lotus Cars': ['SCC'],
  'Alfa': ['ZAS'],
  'KTM': ['VBK'],
  'Chrysler Canada': ['2A4', '2A8', '2C4'],
  'DAF Trucks': ['XLR'],
  'Jaguar': ['178', 'SAD', 'SAJ']
}